version: '3'
services:
  angular-ui:
    build:
      context: ./festival-planner 
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    container_name: angular-ui
    volumes:
      - ./festival-planner:/usr/src/app/festival-planner
      - /usr/src/app/festival-planner/node_modules